### ISSUE TITLE
Display issue - VNC causing display artifacts on scratch 2

### ISSUE THREAD

**Issue by mutrised** [Botspot/scratch2#4]
Hi,

I installed this package on a pi3B+, in order to be able to use scratch with GPIO (scratch3 cannot start and I cannot find any way to get scratch 1.4 to handle GPIOs...).
Ths installation went fine, it is starting, but... There are display issue, the rendering is pretty bad, text is barely readable and even symbols are hardly recognisable...

![Capture](https://github.com/user-attachments/assets/38e57367-4619-4876-bc84-2d33f6710d87)
![image](https://github.com/user-attachments/assets/07840945-a1b1-4a76-92d9-38f1d4481045)

Would you have any clue is it like this and how to fix it ?

I'm on a fresh install of debian bookworm (done yesterday), updated/upgraded right before the installation.

Thanks in advance

Regards
Tristan

**Comment by Botspot** [comment]
Scratch2 is only installable on 32-bit operating systems. This requirement is enforced on the Pi-Apps store where most people install Scratch2 from, but on this repo it appears that no such warning exists. I just tried installing Scratch2 on my PiOS Bookworm 64-bit OS and it worked, but uninstalled a bunch of stuff and replaced it with 32-bit stuff, including the browser.

You have not said which OS version you are using, but if you are using the 64-bit Pi OS, I would suggest flashing your SD card with 32-bit PiOS and see if Scratch2 works better there.

**Comment by mutrised** [comment]
Sorry, I've seen your fast replay, thanks, I just didn't had the time to check on the OS.
I was pretty sure, but I just double checked, it's ARM71, I wouldn't have bothered going for 64bits OS on the rpi3.
But... Since you said it was working on your side, I'll try again from "scratch".
So flashing 32 bits basic Bookworm, then install Pi-Apps store and get Scratch2 from there.

Thanks a lot for your help and for the testing you did on you side. I'll try this today and update the ticket as soon as I have some results.

**Comment by mutrised** [comment]
Thanks for your pi-app, it's really convenient :), I should have gone straight for it but didn't found it quickly enough to avoid messing around...
I still have the issue though... But... I'm using VNC/windows remote desktop to connect to the pi desktop, I need to try with a HDMI display directly to make sure it is not related...
But I must be something on my side (at least now I'm sure about this), I'll investigate.
Thanks for you help, and again, great job for what you've done for making PiOS more user friendly :)
I love so much that fact it is a single bash script ^^

**Comment by mutrised** [comment]
OMG... That's VNC... Through direct HDMI connection there is no issue at all...
I'm sorry for that, I really should have tried this before opening a ticket...
At least it could maybe serve some one else at some point...

I'll see if I found anything related to VNC on the Internet, but in the end, if I need a monitor connected to the Pi it will be fine as well, less practical depending on the Scratch program application but anyway...

I'm marking the ticket as solved since it is not on your side.

Thanks for your help !
Regards
Tristan

**Comment by Botspot** [comment]
No worries at all! In fact, now that you have reported it, I can keep this issue in mind the next time someone reports a similar issue. So rather than wasting my time, you have given me something to potentially use later to help someone else.

I would suggest looking into alternatives to VNC, like RustDesk or [Raspberry Pi Connect](https://www.raspberrypi.com/news/raspberry-pi-connect/).

**Comment by mutrised** [comment]
What a gentleman's answer :)

I'll for sure look into alternatives. That was the first time I tried to use windows remote desktop to reach a linux machine. I usually never use desktops, but for this particular one (scratch for my son), I though it would be better... And that's actually not even really sure...

Anyway, good thing I brought a debug piece to you, and thanks again for these suggestions, I'll dig into it
